### ISSUE TITLE
Doesn't work with PM2 cluster mode

### ISSUE THREAD

**Issue by alesju** [endel/memshared#10]
The following code https://puu.sh/wiTOV/3911ae0365.png
results in nothing but https://puu.sh/wiTQL/70d07a2933.png

Am I doing anything wrong?

**Comment by endel** [comment]
Hey @alesju, your example looks fine. If you imported the `"memshared"` module in both server and workers it should be fine.

**Comment by alesju** [comment]
I use pm2 in cluster mode which uses the cluster module. Since this is handled automatically by pm2 I'm not sure.

**Comment by endel** [comment]
@alesju I see. I've never tried to set this library up with PM2. Will have a look into this. Thanks for reporting!

**Comment by endel** [comment]
We'd need to create a conditional for PM2 and register events differently when using the `cluster` module directly or PM2 here: https://github.com/endel/memshared/blob/af883a21504f95d804efa866f036a60737a237d0/src/index.ts#L37-L51

Here's PM2's documentation on sending messages across processes: http://pm2.keymetrics.io/docs/usage/pm2-api/#send-message-to-process

Also, we'd need to include `pm2` as an `optionalDependencies`.

**Comment by alesju** [comment]
Checking if running under PM2 is as easy as checking process.env.pm_id.

As for supporting PM2, I understand it's something not everybody needs 
but it is a rather popular way to manage node instances or easily 
scaling node applications.

Memshared would be the first shared cache that I know of to support PM2 
clusters if you decide to go through with it.

Endel Dreyer wrote:

**Comment by alesju** [comment]
Do you reckon it would be difficult or time consuming to implement support for this?

**Comment by endel** [comment]
Hey @alesju, I think it shouldn't take much time. I won't have time for this during this month, though. I'd appreciate if you can send me a pull-request!

**Comment by alesju** [comment]
I'd love to do it myself but I'm not really familiar with clustering nor pm2's api to confidently say I can handle it.

**Comment by endel** [comment]
Hey @alesju, I've just found something that looks promising: https://github.com/Unitech/pm2/issues/2044#issuecomment-209254446 
Haven't tested it yet, though.

**Comment by alesju** [comment]
Interesting, but surely there is a way to do cross process talk without the need for punt?

**Comment by alesju** [comment]
Any updates on this?

**Comment by endel** [comment]
Hey @alesju! 

Unfortunately, I'm not focusing on this at the moment. My plan is to work on this in October for Colyseus `v0.6.0+`. Feel free to send a pull-request if you'd like to!

**Comment by endel** [comment]
Hey there! I've finally started implementing this. 

So far, the only way I see to manage the communication between processes is by keeping a "launch bus" always open. 

You'd need a script to spawn the processes and keep listening to the launch bus (`node pm2.js`, which can't be killed in order to keep the communication open with master node): https://github.com/endel/memshared/blob/23eb0283a441e392a09b4fa3db39f2e0b7602da2/pm2/pm2.js

I'm working on the [`pm2`](https://github.com/endel/memshared/tree/pm2) branch. Apparently, the only commands that aren't supported at the moment are `publish` / `subscribe`.

**Comment by endel** [comment]
Just released version `memshared@0.9.18` which supports PM2! 🎉 🎉
