### ISSUE TITLE
Support Key commands

### ISSUE THREAD

**Issue by endel** [endel/memshared#2]
**Essential:**
- [x] DEL key [key ...]
- [x] EXISTS key [key ...]
- [x] RENAME key newkey
- [x] TYPE key
- [x] KEYS pattern

**Comment by barrotsteindev** [comment]
Hello,
I have started working on exists and rename, will post updates soon.

**Comment by endel** [comment]
That's great! Thanks @barrotsteindev :)

**Comment by endel** [comment]
I just implemented some hash commands (#1) if you'd like to have a look at some reference :)

**Comment by endel** [comment]
Hey @barrotsteindev, I've just implemented the essential commands of this issue. It's released on version `0.4.0`
