### ISSUE TITLE
Support Set commands

### ISSUE THREAD

**Issue by endel** [endel/memshared#4]
**Essential:**

- [x] SADD key member [member ...]
- [x] SCARD key
- [x] SISMEMBER key member
- [x] SMEMBERS key
- [x] SREM key member [member ...]
- [x] SRANDMEMBER key [count]
- [x] SPOP key [count]

**Comment by endel** [comment]
Implementation for `sdiff` / `sunion` / `sinter` can be extracted from here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by barrotsteindev** [comment]
started working on srandmemeber

**Comment by endel** [comment]
Yay! Awesome @barrotsteindev :)

**Comment by barrotsteindev** [comment]
Hey,
I just opened a pull request.
https://github.com/endel/memshared/pull/6
